osx_image: xcode7.2
language: objective-c
xcode_project: SimpleKeyChain.xcodeproj
branches:
  only:
    - master
env:
  global:
  - BUILD_XCODE_PROJECT_PATH=SimpleKeyChain.xcodeproj
script:
- xcodebuild clean build test -project $BUILD_XCODE_PROJECT_PATH -scheme SimpleKeyChainLibraryTests -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2' -enableCodeCoverage YES | egrep '^(/.+:[0-9+:[0-9]+:.(error|warning):|fatal|CompileSwift|Test|Build|===)'
after_success:
  - bash <(curl -s https://codecov.io/bash)
coverage:
  notify:
    slack: 
      Library:
        target: 95%
        threshold: 1.25%
        flag: unittests
notifications:
  slack: gcggbsctooffice:JYFXpOunEvNnr7qdslrB1Lu4