osx_image: xcode7.2
language: objective-c
xcode_project: SimpleKeyChain.xcodeproj
branches:
  only:
    - master
env:
  global:
  - BUILD_XCODE_PROJECT_PATH=SimpleKeyChain.xcodeproj
script:
- xcodebuild clean build test -project $BUILD_XCODE_PROJECT_PATH -scheme SimpleKeyChainLibraryTests -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2' -enableCodeCoverage YES | egrep '^(/.+:[0-9+:[0-9]+:.(error|warning):|fatal|CompileSwift|Test|Build|===)'
notifications:
  slack: gcggbsctooffice:JYFXpOunEvNnr7qdslrB1Lu4