osx_image: xcode9.3
language: objective-c
xcode_project: SimpleKeyChain.xcodeproj
branches:
  only:
    - master
env:
  global:
  - BUILD_XCODE_PROJECT_PATH=SimpleKeyChain.xcodeproj
script:
- xcodebuild clean build test -project $BUILD_XCODE_PROJECT_PATH -scheme SimpleKeyChainLibraryTests -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3' -enableCodeCoverage YES | egrep '^(/.+:[0-9+:[0-9]+:.(error|warning):|fatal|CompileSwift|Test|Build|===)'
notifications:
  slack: gcggbsctooffice:JYFXpOunEvNnr7qdslrB1Lu4
after_success:
  - bash <(curl -s https://codecov.io/bash)