codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: 70...100
  notify:
    slack: 
      default:
        url: "https://hooks.slack.com/services/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"
        target: 85%
        threshold: 1.25%
        flag: unittests

  status:
    # Learn more at https://codecov.io/docs#yaml_default_commit_status
    project: true
    patch: true
    changes: true

comment:
  layout: "header, diff, changes, uncovered"
  behavior: default  # update if exists else create new